version: '1'

services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@kvb5fjflzy575qgo_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=Formativa_s4
      - spring.datasource.password=FmatvaS4_1234
    restart: always
